#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/rc/config

curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme -o /usr/bin/gimme
chmod +x /usr/bin/gimme

apk add --no-cache bzr mercurial git go gcc musl-dev

cp ${SOURCE_DIR}/go/Procfile ${SOURCE_DIR}/default/Procfile

echo "GOPATH=${APP_DIR}" >> ${HOME}/.profile
echo 'PATH=$GOPATH:$PATH' >> ${HOME}/.profile
echo 'export PATH GOPATH' >> ${HOME}/.profile
