#!/bin/sh -el

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/rc/config
source ${SOURCE_DIR}/base/deploy

set +e
test -e ${CURRENT_DIR}/nginx.conf && sudo mv ${CURRENT_DIR}/nginx.conf /etc/nginx/nginx.conf
set -e

${SOURCE_DIR}/static/validate-nginx-conf /etc/nginx/nginx.conf
